### ISSUE TITLE
you api key is public

### ISSUE THREAD

**Issue by shaaanuu** [Hitstar53/AI-Clinic-Website#1]
broooo... your api key is public. it should be hidden

**Comment by Hitstar53** [comment]
hello.. thanks for the heads up, its not an issue I think I have already revoked it, ill take it off from the code as well!

**Comment by shaaanuu** [comment]
hmm what i meant is [this](https://github.com/Hitstar53/AI-Clinic-Website/blob/main/key.txt)

**Comment by Hitstar53** [comment]
yes, i know, i have removed it now thanks 👍
